### ISSUE TITLE
Something in 2.2.2 cause my game to crash that didn't happen on 2.2.1

### ISSUE THREAD

**Issue by Aces-and-Jacks** [peanutbutter144/timestamp-chat#5]

**Comment by Aces-and-Jacks** [comment]
with 2.2 https://pastebin.com/PvTnxpiE

**Comment by Aces-and-Jacks** [comment]
with 2.1 https://pastebin.com/6w07aXAj

**Comment by DuendeInexistente** [comment]
Possibly having the same issue. The mixin fails to inject. https://paste.ee/p/s74UB

**Comment by Abbie5** [comment]
I made a mistake in this release, it only supports Minecraft 1.19.1. Please use 2.2.1 on 1.19.

**Comment by Abbie5** [comment]
Version 2.2.4 has been released, which fixes the dependency versioning issue.
